name: Create PR on test repos
on:
  push:
    branches:
      - main
    tags:
      - "!*"
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/create-pr
